# For login related actions and Shopping cart functionality, use the below URL
# url=https://rahulshettyacademy.com/loginpagePractise/

# For AutomationPractice related to actions on elements, use the below URL
url=https://rahulshettyacademy.com/AutomationPractice/


browser=chrome

username=rahulshettyacademy
password=Learning@830$3mK2